import {
  Activity,
  AlarmClock,
  AlertCircle,
  AlertTriangle,
  Anchor,
  Archive,
  ArrowDownUp,
  ArrowRight,
  ArrowUpRight,
  AudioLines,
  Award,
  BadgeCheck,
  Ban,
  Banknote,
  BarChart,
  BarChart3,
  Barcode,
  Battery,
  Beef,
  Bell,
  BellRing,
  Bike,
  Bluetooth,
  Book,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  Car,
  ChartLine,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleHelp,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock3,
  Cloud,
  CloudRain,
  Code,
  Code2,
  Coffee,
  Cog,
  Coins,
  Columns,
  Compass,
  Contact,
  Container,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dices,
  DollarSign,
  Download,
  Droplet,
  ExternalLink,
  Factory,
  File,
  FileAudio,
  FileCheck,
  FileDown,
  FileSpreadsheet,
  FileText,
  Files,
  Filter,
  Flag,
  FlagTriangleRight,
  Flame,
  Flower,
  Folder,
  FolderOpen,
  Forklift,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitCommit,
  GitFork,
  GitPullRequest,
  Globe,
  GraduationCap,
  Grid3x3,
  Hammer,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HelpCircle,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Kanban,
  Key,
  KeyRound,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  LineChart,
  Link,
  List,
  ListChecks,
  ListTodo,
  LoaderCircle,
  Lock,
  LockKeyhole,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MemoryStick,
  Menu,
  Merge,
  MessageCircle,
  MessageCircleQuestion,
  MessagesSquare,
  Mic,
  Mic2,
  Monitor,
  Moon,
  MoreVertical,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  Package,
  Palette,
  PanelLeft,
  Pause,
  PenTool,
  Pencil,
  Percent,
  Phone,
  PieChart,
  Pizza,
  Plane,
  Play,
  PlayCircle,
  Plug,
  Plus,
  Power,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  ReceiptText,
  Recycle,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCw,
  Rows,
  Rss,
  Ruler,
  Scale,
  Scan,
  ScanSearch,
  Scissors,
  ScrollText,
  Search,
  SearchX,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  Sliders,
  Smartphone,
  Snowflake,
  Sparkles,
  Split,
  Square,
  SquarePen,
  Stamp,
  Star,
  StickyNote,
  StopCircle,
  Store,
  Sun,
  Table,
  Tag,
  Tags,
  Target,
  Terminal,
  TerminalSquare,
  Thermometer,
  ThumbsUp,
  Ticket,
  Timer,
  Train,
  Trash,
  Trash2,
  TreePine,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  UploadCloud,
  User,
  UserCheck,
  UserPlus,
  Users,
  Users2,
  UsersRound,
  Utensils,
  Video,
  Volume2,
  Wallet,
  Warehouse,
  Webhook,
  Wifi,
  Wind,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "activity": Activity,
  "alarm-clock": AlarmClock,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "anchor": Anchor,
  "archive": Archive,
  "arrow-down-up": ArrowDownUp,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "audio-lines": AudioLines,
  "award": Award,
  "badge-check": BadgeCheck,
  "ban": Ban,
  "banknote": Banknote,
  "bar-chart": BarChart,
  "bar-chart-3": BarChart3,
  "barcode": Barcode,
  "battery": Battery,
  "beef": Beef,
  "bell": Bell,
  "bell-ring": BellRing,
  "bike": Bike,
  "bluetooth": Bluetooth,
  "book": Book,
  "book-open": BookOpen,
  "bookmark": Bookmark,
  "bookmark-check": BookmarkCheck,
  "bot": Bot,
  "box": Box,
  "boxes": Boxes,
  "brain": Brain,
  "briefcase": Briefcase,
  "brush": Brush,
  "building": Building,
  "building-2": Building2,
  "bus": Bus,
  "cake": Cake,
  "calculator": Calculator,
  "calendar": Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "camera": Camera,
  "car": Car,
  "chart-line": ChartLine,
  "check": Check,
  "check-check": CheckCheck,
  "check-circle": CheckCircle,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "circle": Circle,
  "circle-check": CircleCheck,
  "circle-help": CircleHelp,
  "clipboard": Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "clock-3": Clock3,
  "cloud": Cloud,
  "cloud-rain": CloudRain,
  "code": Code,
  "code-2": Code2,
  "coffee": Coffee,
  "cog": Cog,
  "coins": Coins,
  "columns": Columns,
  "compass": Compass,
  "contact": Contact,
  "container": Container,
  "copy": Copy,
  "cpu": Cpu,
  "credit-card": CreditCard,
  "crown": Crown,
  "database": Database,
  "dices": Dices,
  "dollar-sign": DollarSign,
  "download": Download,
  "droplet": Droplet,
  "external-link": ExternalLink,
  "factory": Factory,
  "file": File,
  "file-audio": FileAudio,
  "file-check": FileCheck,
  "file-down": FileDown,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "files": Files,
  "filter": Filter,
  "flag": Flag,
  "flag-triangle-right": FlagTriangleRight,
  "flame": Flame,
  "flower": Flower,
  "folder": Folder,
  "folder-open": FolderOpen,
  "forklift": Forklift,
  "gamepad-2": Gamepad2,
  "gauge": Gauge,
  "gem": Gem,
  "gift": Gift,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-fork": GitFork,
  "git-pull-request": GitPullRequest,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "grid-3x3": Grid3x3,
  "hammer": Hammer,
  "handshake": Handshake,
  "hard-drive": HardDrive,
  "headphones": Headphones,
  "heart": Heart,
  "help-circle": HelpCircle,
  "history": History,
  "home": Home,
  "image": Image,
  "inbox": Inbox,
  "info": Info,
  "kanban": Kanban,
  "key": Key,
  "key-round": KeyRound,
  "layers": Layers,
  "layout": Layout,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "leaf": Leaf,
  "line-chart": LineChart,
  "link": Link,
  "list": List,
  "list-checks": ListChecks,
  "list-todo": ListTodo,
  "loader-circle": LoaderCircle,
  "lock": Lock,
  "lock-keyhole": LockKeyhole,
  "mail": Mail,
  "map": Map,
  "map-pin": MapPin,
  "megaphone": Megaphone,
  "memory-stick": MemoryStick,
  "menu": Menu,
  "merge": Merge,
  "message-circle": MessageCircle,
  "message-circle-question": MessageCircleQuestion,
  "messages-square": MessagesSquare,
  "mic": Mic,
  "mic-2": Mic2,
  "monitor": Monitor,
  "moon": Moon,
  "more-vertical": MoreVertical,
  "music": Music,
  "navigation": Navigation,
  "network": Network,
  "newspaper": Newspaper,
  "notebook": Notebook,
  "package": Package,
  "palette": Palette,
  "panel-left": PanelLeft,
  "pause": Pause,
  "pen-tool": PenTool,
  "pencil": Pencil,
  "percent": Percent,
  "phone": Phone,
  "pie-chart": PieChart,
  "pizza": Pizza,
  "plane": Plane,
  "play": Play,
  "play-circle": PlayCircle,
  "plug": Plug,
  "plus": Plus,
  "power": Power,
  "printer": Printer,
  "puzzle": Puzzle,
  "qr-code": QrCode,
  "radio": Radio,
  "receipt-text": ReceiptText,
  "recycle": Recycle,
  "refresh-ccw": RefreshCcw,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "rocket": Rocket,
  "rotate-cw": RotateCw,
  "rows": Rows,
  "rss": Rss,
  "ruler": Ruler,
  "scale": Scale,
  "scan": Scan,
  "scan-search": ScanSearch,
  "scissors": Scissors,
  "scroll-text": ScrollText,
  "search": Search,
  "search-x": SearchX,
  "send": Send,
  "server": Server,
  "settings": Settings,
  "share": Share,
  "share-2": Share2,
  "shield": Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "ship": Ship,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "shuffle": Shuffle,
  "sidebar": Sidebar,
  "sliders": Sliders,
  "smartphone": Smartphone,
  "snowflake": Snowflake,
  "sparkles": Sparkles,
  "split": Split,
  "square": Square,
  "square-pen": SquarePen,
  "stamp": Stamp,
  "star": Star,
  "sticky-note": StickyNote,
  "stop-circle": StopCircle,
  "store": Store,
  "sun": Sun,
  "table": Table,
  "tag": Tag,
  "tags": Tags,
  "target": Target,
  "terminal": Terminal,
  "terminal-square": TerminalSquare,
  "thermometer": Thermometer,
  "thumbs-up": ThumbsUp,
  "ticket": Ticket,
  "timer": Timer,
  "train": Train,
  "trash": Trash,
  "trash-2": Trash2,
  "tree-pine": TreePine,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  "trophy": Trophy,
  "truck": Truck,
  "tv": Tv,
  "upload-cloud": UploadCloud,
  "user": User,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "users": Users,
  "users-2": Users2,
  "users-round": UsersRound,
  "utensils": Utensils,
  "video": Video,
  "volume-2": Volume2,
  "wallet": Wallet,
  "warehouse": Warehouse,
  "webhook": Webhook,
  "wifi": Wifi,
  "wind": Wind,
  "workflow": Workflow,
  "wrench": Wrench,
  "x": X,
  "x-circle": XCircle,
  "zap": Zap,
};
